from typing import Any
from django.urls import reverse
from django.db import models
from PIL import Image
from django.forms import ModelForm


# Create your models here.

class User(models.Model):

    name = models.CharField(max_length=50)
        #Optional "about"   field, from https://stackoverflow.com/questions/16349545/optional-fields-in-django-models
    about = models.CharField(max_length=1000, blank=True, default='')
    contact_email = models.CharField(max_length=200) 
    
    #Define default String to return the name for representing the Model object."
    def __str__(self):
        return self.name

    def __getattribute__(self, __name: str) -> Any:
        return super().__getattribute__(__name)

    #Returns the URL to access a particular instance of MyModelName.
    #if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])
#end User class


class CardDeck(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) #Removed: , null=True
    description = models.CharField(max_length=500) 
    is_active = models.CharField(max_length=5, default='False')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        #Autogenerated: 
        #return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse('carddeck-detail', args=[str(self.id)])
#end CardDeck class    

class Card(models.Model):
    title = models.CharField(max_length=200)
    question = models.CharField(max_length=1000)
    #Each card must have an assigned carddeck
    carddeck = models.ForeignKey(CardDeck, on_delete=models.CASCADE, null=True)
    
    option_1 = models.CharField(max_length=200)
    option_2 = models.CharField(max_length=200) 
    option_3 = models.CharField(max_length=200)
    option_4 = models.CharField(max_length=200)

    correct_option = models.CharField(max_length=200)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        #Autogenerated: 
        # return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse('card-detail', args=[str(self.id)])    
#end Card class


#From https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/#top
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['name', 'about', 'contact_email']

# Creating a form to add an User.
user_form = UserForm()

# Creating a form to change an existing User.
user = User.objects.get(pk=1)
form = UserForm(instance=user)