from typing import Any
from django.urls import reverse
from django.db import models

# Create your models here.

class CardDeck(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50) 
    description = models.CharField(max_length=500) 
    is_active = models.CharField(max_length=5, default='False')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        #Autogenerated: 
        #return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse('carddeck-detail', args=[str(self.id)])
#end CardDeck class    


class User(models.Model):

    name = models.CharField(max_length=50)
        #Optional "about"   field, from https://stackoverflow.com/questions/16349545/optional-fields-in-django-models
    about = models.CharField(max_length=1000, blank=True, default='')
    contact_email = models.CharField(max_length=200) 
    CardDeck = models.OneToOneField(CardDeck, on_delete=models.CASCADE, unique=True, default=None)
        #CardDeck = models.ForeignKey(CardDeck, on_delete=models.CASCADE, unique=True, default=None)

    #Define default String to return the name for representing the Model object."
    def __str__(self):
        return self.name

    def __getattribute__(self, __name: str) -> Any:
        return super().__getattribute__(__name)

    #Returns the URL to access a particular instance of MyModelName.
    #if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])
#end User class


class Card(models.Model):
    title = models.CharField(max_length=200)
    question = models.CharField(max_length=1000)
    #Not sure if correct
    #carddeck = models.OneToOneField(CardDeck, on_delete=models.CASCADE, unique=True, default=None)
    carddeck = models.ForeignKey(CardDeck, on_delete=models.CASCADE, default = None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        #Autogenerated: 
        # return reverse("model_detail", kwargs={"pk": self.pk})
        return reverse('card-detail', args=[str(self.id)])    
#end Card class