# Generated by Django 4.2.6 on 2023-11-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.CharField(default='False', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(blank=True, default='', max_length=1000)),
                ('contact_email', models.CharField(max_length=200)),
                ('CardDeck', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.carddeck')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=1000)),
                ('carddeck', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.carddeck')),
            ],
        ),
    ]
