# Generated by Django 4.2.7 on 2023-11-26 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddeck',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CardDeck',
        ),
        migrations.AddField(
            model_name='carddeck',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='carddeck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.carddeck'),
        ),
    ]
