# Generated by Django 4.2.7 on 2023-11-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0002_remove_carddeck_author_remove_user_carddeck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddeck',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.user'),
        ),
    ]
