# Generated by Django 4.2.7 on 2023-11-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0003_alter_carddeck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddeck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.user'),
            preserve_default=False,
        ),
    ]
