# Generated by Django 4.2.7 on 2023-11-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0004_alter_carddeck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='option_1',
            field=models.CharField(default=333, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='option_2',
            field=models.CharField(default=334, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='option_3',
            field=models.CharField(default=335, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='option_4',
            field=models.CharField(default=336, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_app.user'),
        ),
    ]
