# Generated by Django 4.2.7 on 2023-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0005_card_option_1_card_option_2_card_option_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddeck',
            name='image',
            field=models.ImageField(default=111, upload_to='images/'),
            preserve_default=False,
        ),
    ]
