# Generated by Django 4.2.7 on 2023-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0006_carddeck_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct_option',
            field=models.CharField(default=222, max_length=200),
            preserve_default=False,
        ),
    ]
