# Generated by Django 4.2.6 on 2023-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0006_carddeck_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct_option',
            field=models.CharField(default='filler text', max_length=200),
        ),
    ]
