# Generated by Django 4.2.6 on 2023-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0007_card_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddeck',
            name='image',
            field=models.ImageField(default='navbar_logo.png', upload_to='images/'),
        ),
    ]
